export { AtlasToolBase, type IAtlasConfig, type IAtlasSession } from "./atlasTool.js";
export {
    ListClustersTool,
    ListClustersArgs,
    ListProjectsTool,
    ListDBUsersTool,
    ListDBUsersArgs,
    ListAlertsTool,
    ListAlertsArgs,
    ListOrganizationsTool,
    InspectClusterTool,
    InspectClusterArgs,
    InspectAccessListTool,
    InspectAccessListArgs,
    GetPerformanceAdvisorTool,
    CreateProjectTool,
    CreateDBUserTool,
    CreateDBUserArgs,
    CreateFreeClusterTool,
    CreateAccessListTool,
    CreateAccessListArgs,
    ConnectClusterTool,
    ConnectClusterArgs,
    StreamsDiscoverTool,
    StreamsBuildTool,
    StreamsManageTool,
    StreamsTeardownTool,
} from "./tools/tools.js";

import {
    ListClustersTool,
    ListProjectsTool,
    InspectClusterTool,
    CreateFreeClusterTool,
    CreateAccessListTool,
    InspectAccessListTool,
    ListDBUsersTool,
    CreateDBUserTool,
    CreateProjectTool,
    ListOrganizationsTool,
    ConnectClusterTool,
    ListAlertsTool,
    GetPerformanceAdvisorTool,
    StreamsDiscoverTool,
    StreamsBuildTool,
    StreamsManageTool,
    StreamsTeardownTool,
} from "./tools/tools.js";
import type { ToolClass } from "@mongodb-js/mcp-core";
export const AtlasTools: ToolClass[] = [
    ListClustersTool,
    ListProjectsTool,
    InspectClusterTool,
    CreateFreeClusterTool,
    CreateAccessListTool,
    InspectAccessListTool,
    ListDBUsersTool,
    CreateDBUserTool,
    CreateProjectTool,
    ListOrganizationsTool,
    ConnectClusterTool,
    ListAlertsTool,
    GetPerformanceAdvisorTool,
    StreamsDiscoverTool,
    StreamsBuildTool,
    StreamsManageTool,
    StreamsTeardownTool,
];
