/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:ui
 *
 * Lazy loaders for UI modules. Each loader returns a Promise<string> with the HTML.
 */
export const appLoaders: Record<string, () => Promise<string>> = {
    "explain": async () => {
        const mod = await import("./apps/explain.js");
        return mod.ExplainAppHtml;
    }
};
