packages:
  - "packages/*"
  - "tests/browser"
overrides:
  "mongodb": "7.1.1"
  "kerberos": "^7.0.0"
  "bson": "^7.3.3"
  "zod": "^4.6.5"
allowBuilds:
  "@modelcontextprotocol/ext-apps": false
  "@modelcontextprotocol/inspector": true
  braintrust: true
  core-js: false
  cpu-features: true
  esbuild: true
  kerberos: true
  macos-export-certificate-and-key: true
  mongodb-client-encryption: true
  os-dns-native: true
  protobufjs: true
  ssh2: true
  win-export-certificate-and-key: true
minimumReleaseAgeExclude:
  - mongodb-runner@6.7.13
  - "@mongodb-js/devtools-proxy-support@0.7.19"
  - "@microsoft/api-extractor-model@7.33.9"
  - "@microsoft/api-extractor@7.58.10"
  - "@rushstack/node-core-library@5.23.2"
  - "@rushstack/terminal@0.24.1"
  - "@rushstack/ts-command-line@5.3.11"
  - '@ai-sdk/anthropic@4.0.62'
  - '@ai-sdk/azure@4.0.78'
  - '@ai-sdk/deepseek@3.0.52'
  - '@ai-sdk/gateway@4.0.91'
  - '@ai-sdk/google@4.0.79'
  - '@ai-sdk/mcp@2.0.57'
  - '@ai-sdk/openai@4.0.74'
  - '@ai-sdk/provider-utils@5.0.47'
  - '@modelcontextprotocol/inspector@2.8.0'
  - ai@7.0.113
  - braintrust@3.35.0
  - vite@8.3.1
