/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:apps
 *
 * Lazy loaders for app modules. Each loader returns a Promise<string> with the HTML.
 */
export const appLoaders: Record<string, () => Promise<string>> = {
    "connect-form": async () => {
        const mod = await import("./apps/connect-form.js");
        return mod.ConnectFormHtml;
    }
};
