/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm compile
 *
 * Lazy loaders for app modules. Each loader returns a Promise<string> with the HTML.
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

async function devReadApp(filePath: string): Promise<string> {
    const content = await readFile(filePath, "utf-8");
    const match = /export const \w+Html = ("(?:[^"\\]|\\[\s\S])*");/.exec(content);
    if (!match?.[1]) throw new Error(`Could not extract HTML from ${filePath}`);
    return JSON.parse(match[1]) as string;
}

export const appLoaders: Record<string, () => Promise<string>> = {
    "connect-form": async () => {
        if (process.env.MCPAPP_DEV) return devReadApp(join(__dirname, "apps/connect-form.js"));
        const mod = await import("./apps/connect-form.js");
        return mod.ConnectFormHtml;
    },
    "document-browser": async () => {
        if (process.env.MCPAPP_DEV) return devReadApp(join(__dirname, "apps/document-browser.js"));
        const mod = await import("./apps/document-browser.js");
        return mod.DocumentBrowserHtml;
    }
};
