---
name: "Bug Report"
description: "Report a bug to help us improve."
title: "[Bug]: "
type: "Bug"
body:
  - type: markdown
    attributes:
      value: "Please fill out the following details to help us address the issue."
  - type: checkboxes
    id: app
    attributes:
      label: "App"
      description: "Select the app where the bug occurred."
      options:
        - label: Cursor
        - label: Windsurf
        - label: VSCode
        - label: VSCode Insiders
        - label: Claude Desktop
        - label: Other
  - type: checkboxes
    id: affected_models
    attributes:
      label: "Affected Models (if applicable)"
      description: "Select the models affected by the bug."
      options:
        - label: "Claude 3.5 Sonnet"
        - label: "Claude 3.7 Sonnet"
        - label: "GPT-4a"
        - label: "o4-mini"
        - label: "Other"
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Describe the bug in detail. Include steps to reproduce, expected behavior, and actual behavior."
      placeholder: "e.g., When I prompt connect to mongodb, it crashes with error XYZ."
    validations:
      required: true
