import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import { viteSingleFile } from "vite-plugin-singlefile";
import { nodePolyfills } from "vite-plugin-node-polyfills";
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync, rmSync } from "fs";
import { join, resolve } from "path";

const appsDir = resolve(__dirname, "src/apps");
const entriesDir = resolve(__dirname, "node_modules/.cache/mcp-apps/app-entries");
const templatePath = resolve(__dirname, "src/build/template.html");
const mountPath = resolve(__dirname, "src/build/mount.tsx");
const generatedDir = resolve(__dirname, "src/lib");
const appsDistPath = resolve(__dirname, "dist/apps");

function toKebabCase(pascalCase: string): string {
    return pascalCase
        .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
        .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
        .toLowerCase();
}

function discoverApps(): { apps: string[]; appNameToComponentMap: Record<string, string> } {
    const apps: string[] = [];
    const appNameToComponentMap: Record<string, string> = {};

    for (const entry of readdirSync(appsDir)) {
        const entryPath = join(appsDir, entry);
        const indexPath = join(entryPath, "index.ts");

        if (statSync(entryPath).isDirectory() && existsSync(indexPath)) {
            apps.push(entry);
            appNameToComponentMap[toKebabCase(entry)] = entry;
        }
    }

    return { apps, appNameToComponentMap };
}

const { apps, appNameToComponentMap } = discoverApps();

function generateHtmlEntries(): Plugin {
    return {
        name: "generate-html-entries",
        buildStart(): void {
            const template = readFileSync(templatePath, "utf-8");

            if (!existsSync(entriesDir)) {
                mkdirSync(entriesDir, { recursive: true });
            }

            for (const componentName of apps) {
                const html = template
                    .replace("{{COMPONENT_NAME}}", componentName)
                    .replace("{{TITLE}}", componentName.replace(/([A-Z])/g, " $1").trim())
                    .replace("{{MOUNT_PATH}}", mountPath);

                const outputPath = join(entriesDir, `${componentName}.html`);
                writeFileSync(outputPath, html);
                console.log(`[generate-html-entries] Generated ${componentName}.html`);
            }
        },
    };
}

function generateAppModules(): Plugin {
    return {
        name: "generate-app-modules",
        closeBundle(): void {
            if (!existsSync(appsDistPath)) {
                console.warn("[generate-app-modules] dist/apps not found, skipping module generation");
                return;
            }

            const appsLibDir = join(generatedDir, "apps");
            mkdirSync(appsLibDir, { recursive: true });
            const existingAppFiles = readdirSync(appsLibDir).filter((file) => file.endsWith(".ts"));

            const generatedApps: string[] = [];

            for (const [appName, componentName] of Object.entries(appNameToComponentMap)) {
                const htmlFile = join(appsDistPath, `${componentName}.html`);
                if (!existsSync(htmlFile)) {
                    console.warn(
                        `[generate-app-modules] HTML file not found for component "${componentName}" (app: "${appName}")`
                    );
                    continue;
                }
                const html = readFileSync(htmlFile, "utf-8");

                const appModuleContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: vite build --config vite.apps.config.ts
 * App: ${appName}
 * Component: ${componentName}
 */
export const ${componentName}Html = ${JSON.stringify(html)};
`;
                writeFileSync(join(appsLibDir, `${appName}.ts`), appModuleContent);
                generatedApps.push(appName);
            }

            const loaderEntries = generatedApps
                .map((appName) => {
                    const componentName = appNameToComponentMap[appName];
                    return `    "${appName}": async () => {
        const mod = await import("./apps/${appName}.js");
        return mod.${componentName}Html;
    }`;
                })
                .join(",\n");

            const loadersContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm generate:apps
 *
 * Lazy loaders for app modules. Each loader returns a Promise<string> with the HTML.
 */
export const appLoaders: Record<string, () => Promise<string>> = {
${loaderEntries}
};
`;
            writeFileSync(join(generatedDir, "loaders.ts"), loadersContent);

            console.log(
                `[generate-app-modules] Generated ${generatedApps.length} app module(s): ${generatedApps.join(", ")}`
            );
            console.log(`[generate-app-modules] Generated loaders.ts with ${generatedApps.length} loader(s)`);

            const staleApps = existingAppFiles.filter((file) => {
                const appName = file.replace(/\.ts$/, "");
                return !generatedApps.includes(appName);
            });
            for (const staleApp of staleApps) {
                rmSync(join(appsLibDir, staleApp));
                console.log(`[generate-app-modules] Removed stale app module: ${staleApp}`);
            }

            if (existsSync(appsDistPath)) {
                rmSync(appsDistPath, { recursive: true });
                console.log("[generate-app-modules] Cleaned up intermediate dist/apps directory");
            }
        },
    };
}

export default defineConfig({
    root: entriesDir,
    plugins: [
        generateHtmlEntries(),
        nodePolyfills({
            include: ["buffer", "stream"],
            globals: {
                Buffer: true,
            },
        }),
        react(),
        viteSingleFile({
            removeViteModuleLoader: true,
        }),
        generateAppModules(),
    ],
    build: {
        outDir: resolve(__dirname, "dist/apps"),
        emptyOutDir: true,
        rollupOptions: {
            input: Object.fromEntries(apps.map((name) => [name, resolve(entriesDir, `${name}.html`)])),
        },
        assetsInlineLimit: 100000000,
        sourcemap: false,
        minify: "esbuild",
    },
    resolve: {
        alias: {
            "@apps": resolve(__dirname, "src"),
        },
    },
});
