/**
 * Programmatic build script for MCP Apps.
 *
 * Each app must be a self-contained single HTML file (viteSingleFile), which requires
 * inlineDynamicImports / codeSplitting:false. Rollup rejects that option when there are
 * multiple inputs in one build, so we run one Vite build per app and combine the outputs
 * afterward via generateAppModules().
 */
import { build } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { viteSingleFile } from "vite-plugin-singlefile";
import { nodePolyfills } from "vite-plugin-node-polyfills";
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync, rmSync } from "fs";
import { join, resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");

const appsDir = resolve(rootDir, "src/apps");
const entriesDir = resolve(rootDir, "node_modules/.cache/mcp-apps/app-entries");
const templatePath = resolve(rootDir, "src/build/template.html");
const mountPath = resolve(rootDir, "src/build/mount.tsx");
const generatedDir = resolve(rootDir, "src/lib");
const appsDistPath = resolve(rootDir, "dist/apps");

function toKebabCase(pascalCase: string): string {
    return pascalCase
        .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
        .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
        .toLowerCase();
}

function discoverApps(): { apps: string[]; appNameToComponentMap: Record<string, string> } {
    const apps: string[] = [];
    const appNameToComponentMap: Record<string, string> = {};
    for (const entry of readdirSync(appsDir)) {
        const entryPath = join(appsDir, entry);
        const indexPath = join(entryPath, "index.ts");
        if (statSync(entryPath).isDirectory() && existsSync(indexPath)) {
            apps.push(entry);
            appNameToComponentMap[toKebabCase(entry)] = entry;
        }
    }
    return { apps, appNameToComponentMap };
}

function generateHtmlEntries(apps: string[]): void {
    const template = readFileSync(templatePath, "utf-8");
    if (!existsSync(entriesDir)) {
        mkdirSync(entriesDir, { recursive: true });
    }
    for (const componentName of apps) {
        const html = template
            .replace("{{COMPONENT_NAME}}", componentName)
            .replace("{{TITLE}}", componentName.replace(/([A-Z])/g, " $1").trim())
            .replace("{{MOUNT_PATH}}", mountPath);
        const outputPath = join(entriesDir, `${componentName}.html`);
        writeFileSync(outputPath, html);
        console.log(`[generate-html-entries] Generated ${componentName}.html`);
    }
}

function generateAppModules(appNameToComponentMap: Record<string, string>): void {
    if (!existsSync(appsDistPath)) {
        console.warn("[generate-app-modules] dist/apps not found, skipping module generation");
        return;
    }

    const appsLibDir = join(generatedDir, "apps");
    mkdirSync(appsLibDir, { recursive: true });
    const existingAppFiles = readdirSync(appsLibDir).filter((file) => file.endsWith(".ts"));

    const generatedApps: string[] = [];

    for (const [appName, componentName] of Object.entries(appNameToComponentMap)) {
        const htmlFile = join(appsDistPath, `${componentName}.html`);
        if (!existsSync(htmlFile)) {
            console.warn(
                `[generate-app-modules] HTML file not found for component "${componentName}" (app: "${appName}")`
            );
            continue;
        }
        const html = readFileSync(htmlFile, "utf-8");
        const appModuleContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm compile
 * App: ${appName}
 * Component: ${componentName}
 */
export const ${componentName}Html = ${JSON.stringify(html)};
`;
        writeFileSync(join(appsLibDir, `${appName}.ts`), appModuleContent);
        generatedApps.push(appName);
    }

    const loaderEntries = generatedApps
        .map((appName) => {
            const componentName = appNameToComponentMap[appName];
            return `    "${appName}": async () => {
        if (process.env.MCPAPP_DEV) return devReadApp(join(__dirname, "apps/${appName}.js"));
        const mod = await import("./apps/${appName}.js");
        return mod.${componentName}Html;
    }`;
        })
        .join(",\n");

    const loadersContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: pnpm compile
 *
 * Lazy loaders for app modules. Each loader returns a Promise<string> with the HTML.
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

async function devReadApp(filePath: string): Promise<string> {
    const content = await readFile(filePath, "utf-8");
    const match = /export const \\w+Html = ("(?:[^"\\\\]|\\\\[\\s\\S])*");/.exec(content);
    if (!match?.[1]) throw new Error(\`Could not extract HTML from \${filePath}\`);
    return JSON.parse(match[1]) as string;
}

export const appLoaders: Record<string, () => Promise<string>> = {
${loaderEntries}
};
`;
    writeFileSync(join(generatedDir, "loaders.ts"), loadersContent);

    console.log(`[generate-app-modules] Generated ${generatedApps.length} app module(s): ${generatedApps.join(", ")}`);
    console.log(`[generate-app-modules] Generated loaders.ts with ${generatedApps.length} loader(s)`);

    const staleApps = existingAppFiles.filter((file) => !generatedApps.includes(file.replace(/\.ts$/, "")));
    for (const staleApp of staleApps) {
        rmSync(join(appsLibDir, staleApp));
        console.log(`[generate-app-modules] Removed stale app module: ${staleApp}`);
    }

    if (existsSync(appsDistPath)) {
        rmSync(appsDistPath, { recursive: true });
        console.log("[generate-app-modules] Cleaned up intermediate dist/apps directory");
    }
}

const { apps, appNameToComponentMap } = discoverApps();

generateHtmlEntries(apps);

for (const [i, componentName] of apps.entries()) {
    await build({
        root: entriesDir,
        plugins: [
            nodePolyfills({ include: ["buffer", "stream"], globals: { Buffer: true } }),
            react(),
            tailwindcss(),
            viteSingleFile({ removeViteModuleLoader: true }),
        ],
        build: {
            outDir: appsDistPath,
            emptyOutDir: i === 0,
            rollupOptions: {
                input: { [componentName]: resolve(entriesDir, `${componentName}.html`) },
            },
            assetsInlineLimit: 100000000,
            sourcemap: false,
            minify: "esbuild",
        },
        resolve: {
            alias: { "@apps": resolve(rootDir, "src") },
        },
    });
}

generateAppModules(appNameToComponentMap);
