// This file was generated by scripts/updatePackageVersion.ts - Do not edit it manually.
export const packageInfo: {
    version: string;
    mcpServerName: string;
    engines: { node: string };
} = {
    version: "1.9.1-prerelease.1",
    mcpServerName: "MongoDB MCP Server",
    engines: {
        node: "^20.19.0 || ^22.12.0 || >= 23.0.0",
    },
};
