// This file was generated by scripts/updatePackageVersion.ts - Do not edit it manually.
export const packageInfo = {
    version: "1.8.2-prerelease.2",
    mcpServerName: "MongoDB MCP Server",
    engines: {
        node: "^20.19.0 || ^22.12.0 || >= 23.0.0",
    },
};
