import type { UserConfig } from "../../common/config/userConfig.js";
import type { LoggerBase } from "../../common/logger.js";
import type { CommonProperties } from "../../telemetry/types.js";
import type { ToolClass } from "../../tools/tool.js";

export type CommonTransportRunnerConfig = {
    /**
     * The schema version of the runner config being provided. When
     * schemaVersion is not provided or is `undefined`, the configuration is
     * treated as legacy configuration.
     */
    schemaVersion?: undefined | number;
    /**
     * Base user configuration for the server.
     *
     * Can be generated by parsing CLI arguments, environment variables or
     * written manually while conforming the interface requirements of
     * `UserConfig`.
     *
     * To parse CLI arguments and environment variables in order to generate a
     * `UserConfig` object, you can use `parseUserConfig` function, also
     * exported as `parseUserConfig` through MCP server library
     * exports.
     *
     * Optionally, you can also use `UserConfigSchema` (available through MCP
     * server library exports) to create a default configuration -
     * `UserConfigSchema.parse({})`.
     */
    userConfig: UserConfig;

    /**
     * An optional list of loggers to be used in addition to the default logger
     * implementations. When not provided, MongoDB MCP Server will not utilize
     * any loggers other than the default that it works with.
     *
     * Customize this only if the default enabled loggers (disk/stderr/mcp) are
     * not covering your use-case.
     */
    additionalLoggers?: LoggerBase[];

    /**
     * An optional key value pair of telemetry properties that are reported to
     * the telemetry backend. Most, if not all, of the properties are captured
     * automatically.
     */
    telemetryProperties?: Partial<CommonProperties>;

    /**
     * An optional list of tools constructors to be registered to the MongoDB
     * MCP Server.
     *
     * When not provided, MongoDB MCP Server will register all internal tools.
     * When specified, **only** the tools in this list will be registered.
     *
     * This allows you to:
     * - Register only custom tools (excluding all internal tools)
     * - Register a subset of internal tools alongside custom tools
     * - Register all internal tools plus custom tools
     *
     * To include internal tools, import them from `mongodb-mcp-server/tools`:
     *
     * ```typescript
     * import { AllTools, AggregateTool, FindTool } from "mongodb-mcp-server/tools";
     *
     * // Register all internal tools plus custom tools
     * tools: [...AllTools, MyCustomTool]
     *
     * // Register only specific MongoDB tools plus custom tools
     * tools: [AggregateTool, FindTool, MyCustomTool]
     *
     * // Register all internal tools of mongodb category
     * tools: [AllTools.filter((tool) => tool.category === "mongodb")]
     * ```
     *
     * Note: Ensure that each tool has unique names otherwise the server will
     * throw an error when initializing an MCP Client session. If you're using
     * only the internal tools, then you don't have to worry about it unless,
     * you've overridden the tool names.
     *
     * To ensure that you provide compliant tool implementations extend your
     * tool implementation using `ToolBase` class and ensure that they conform
     * to `ToolClass` type.
     *
     * @see {@link ToolClass} for the type that tool classes must conform to
     * @see {@link ToolBase} for base class for all the tools
     */
    tools?: ToolClass[];
};
