---
name: "Cleanup stale Atlas test environments"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  cleanup-envs:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run cleanup script
        env:
          MDB_MCP_API_CLIENT_ID: ${{ secrets.TEST_ATLAS_CLIENT_ID }}
          MDB_MCP_API_CLIENT_SECRET: ${{ secrets.TEST_ATLAS_CLIENT_SECRET }}
          MDB_MCP_API_BASE_URL: ${{ vars.TEST_ATLAS_BASE_URL }}
        run: npm run atlas:cleanup
