---
name: Enable Auto Merge on Dependabot PRs
on:
  pull_request:

permissions: {}

jobs:
  merge-dependabot-pr:
    name: Merge Dependabot PR
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
